Simplier concurrency conditionals

diff --git a/.github/workflows/check-function.yml b/.github/workflows/check-function.yml
--- a/.github/workflows/check-function.yml
+++ b/.github/workflows/check-function.yml
@@ -2,10 +2,16 @@
 name: Find Gcloud Function
 on:
   workflow_call:
+    inputs:
+      retry:
+        type: boolean
+        default: false
+        description: "To keep searching for the function"
     outputs:
       function_URL: 
         value: ${{ jobs.check_function_exists.outputs.function_url}}
         description: "function URL (if found) or empty otherwise"
+
 jobs:
   check_function_exists:
     outputs:
@@ -31,13 +37,34 @@ jobs:
           service_account: '${{ secrets.GSA }}'
 
       # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
-      - name: 'Set up Cloud SDK'
-        uses: 'google-github-actions/setup-gcloud@v1' 
+      - name: Set up Cloud SDK
+        uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # v1.0.1
 
-      - name: find-function
+      - name: Discover function URL for website
+        if: inputs.retry != '' || inputs.retry == 'true'
+        shell: bash
+        # max_retry and sleep will consume GHA minutes. It shuold only fail when a PR is still to be deployed though
+        # Initial value: 6 * 60(sleep)
+        run: |
+          echo "Called from website job, keep searching for function"
+          max_retry=6
+          counter=0
+          while ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null && [ $counter -lt $max_retry ]
+          do
+            sleep 60
+            echo "Trying again. Try #$counter"
+            ((counter++))
+          done
+          if ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null; then
+            echo "::error title=Not_found::Function ${{ steps.deploy_vars.outputs.function_name }} not found, check functions deploy and re-run this job"
+          fi
+
+
+      - name: Fetch function URL
         id: find_function
         shell: bash
         run: |
+         echo "Called from function job, return result immediately"
           if gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null; then
            # this will run if function was found
             echo "function_url=$(gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} --format='value(httpsTrigger.url)')" >> $GITHUB_OUTPUT
