figuring out bash in GH shell

diff --git a/.github/workflows/check-function.yml b/.github/workflows/check-function.yml
--- a/.github/workflows/check-function.yml
+++ b/.github/workflows/check-function.yml
@@ -47,15 +47,21 @@ jobs:
         # Initial value: 6 * 60(sleep)
         run: |
           echo "Called from website job, keep searching for function"
-          max_retry=6
+          gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }}
+          max_retry=7
           counter=0
-          while ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null && [ $counter -lt $max_retry ]
+          while ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null && 
+                  [ ${counter} -lt ${max_retry} ]
           do
+            echo " Function not found - Try #${counter}"
+            echo "Wait 1 min..."
+            # Try once every minute
             sleep 60
-            echo "Trying again. Try #$counter"
-            ((counter++))
+            echo "Trying again:"
+            counter=$((counter+1))
+            
           done
-          if ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }} &> /dev/null; then
+          if ! gcloud functions describe --region ${{ vars.GCP_REGION }} ${{ steps.deploy_vars.outputs.function_name }}; then
             echo "::error title=Not_found::Function ${{ steps.deploy_vars.outputs.function_name }} not found, check functions deploy and re-run this job"
             exit 1
           fi
